apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: spacetraders
build:
  local:
  artifacts:
    - image: spacetraders 
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/deployment.yaml
