apiVersion: v1
kind: ServiceAccount
metadata:
  name: spacetraders-operator 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator 
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operator 
subjects:
- kind: ServiceAccount
  name: spacetraders-operator 
  namespace: default
roleRef: 
  kind: ClusterRole
  name: operator 
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spacetraders 
  labels:
    app: spacetraders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spacetraders 
  template:
    metadata:
      labels:
        app: spacetraders 
    spec:
      serviceAccountName: spacetraders-operator
      containers:
      - name: spacetraders 
        image: spacetraders 
        volumeMounts:
          - mountPath: /data/db
            name: db
      volumes:
        - hostPath:
            path: /spacetraders/db
          name: db
