[package]
name = "cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
api = { path = "../api" }

anyhow.workspace = true
clap.workspace = true
tokio.workspace = true
toml.workspace = true
